# server config
domainUrl: "youcai.abiz.com"
appName: "优采个人版"
version: "1.0.0"
clientType: "PC_WEB"
title: "优采个人版"
clusters: false
port: 5000
devMode: false
logLevel: "INFO"
logDist: "d:\\log"
# 2017 车崇源
# 10.10.12.124:8050 杨星
# 10.10.12.96:8050 许晓文
# 9046 刘玉杰
# 10.10.12.130:8050 王正宇
# 192.168.0.195:8050 测试服务器
# 2021 胡聪
# 9055 刘天水
# 9032 李林

backendUrl: "http://192.168.0.195:8050"
cdBackendUrl: "http://cd.abiz.com"
cnMobileBackendUrl: "http://192.168.0.155:7088"
abizBackendUrl: "http://192.168.1.46:8081"
tulipBackendUrl: "http://192.168.0.155:8989"
# 内贸站小程序后台系统
voBackendUrl: "http://192.168.0.178:7002"
socketTimeout: 60000
# 文件处理超时时间
fileSocketTimeout: 180000
cdn: ""
encoding: "utf8"
